name: XGBoost-Python-Tests

on: [push, pull_request]

jobs:
  python-tests-on-win:
    name: Test XGBoost Python package on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: windows-2016, python-version: '3.8'}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.config.python-version }}
        activate-environment: win64_env
        environment-file: tests/ci_build/conda_env/win64_test.yml

    - name: Display Conda env
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Build XGBoost on Windows
      shell: bash -l {0}
      run: |
        mkdir build_msvc
        cd build_msvc
        cmake .. -G"Visual Studio 15 2017" -DCMAKE_CONFIGURATION_TYPES="Release" -A x64 -DGOOGLE_TEST=ON -DUSE_DMLC_GTEST=ON -DUSE_ARROW=ON
        cmake --build . --config Release --parallel $(nproc)

    - name: Install Python package
      shell: bash -l {0}
      run: |
        cd python-package
        python --version
        python setup.py bdist_wheel --universal
        pip install ./dist/*.whl

    - name: Test Python package
      shell: bash -l {0}
      run: |
        pytest -s -v -rA ./tests/python/test_with_arrow.py
